### PR TITLE
WDL grammar.hgr file update 

### PR DESCRIPTION
**Pull request by daniilsavchuk**
## General idea
In last two mounths WDL grammar hosted on [WDL GitHub](https://github.com/broadinstitute/wdl) repository was changed. Currently some requested features are not supported (e.g. expressions into the scatter iteration array).

## Changes
- Updated grammar in order to hosted repository
- Rebuilt the parser
- Updated expression extractor function (because ternary IfThenElse appeared)
- Updated tests 

NOTE - please let me know before PR will be merged. I have to select suitable package.json version for npm registry.

### CODE REVIEW

**Review by voidest — APPROVED** [review]
OK

**Review by paulsmirnov — APPROVED** [review]

**Comment by sidoruka** [comment]
@daniilsavchuk , could you please rebase this PR onto #20 and set appropriate package version? I'll merge this PR after that.
Also I think that we shall discuss some approach to such tasks, how to make sure that we are using latest grammar version.

**Comment by daniilsavchuk** [comment]
@sidoruka [PR#24](https://github.com/epam/pipeline-builder/pull/24/) rebased on to desired brunch. Version is patched. It seem that PR ready to be merged. 

The method of in time updating grammar have to be discussed in case of it's difficulty.
Thank you!

**Comment by daniilsavchuk** [comment]
@sidoruka could we delete the branch after merge? This issue caused [PR#24](https://github.com/epam/pipeline-builder/pull/24) and [PR#18](https://github.com/epam/pipeline-builder/pull/18). Let me delete the origin branches if them aren't still necessary to be stored on repo.

**Pull request merged**
