### PR TITLE
Workflow level inputs/outputs

### PR DESCRIPTION
**Pull request by voidest**
## General idea
At the moment, workflow is not shown on the diagram, which makes user unable to manage links between worklow and its children. This feature was requested in #10. Unfortunaly, on comples diagarams workflow has too many links wis children and they occupy too much visual space and hinder visual perception. Therefore, port toggling was implemented. By **shift-clicking on port** one can enable/disable it. Workflow ports are disabled by default.

## Changes
Added visual port toggling mechanism, added VisualWorkflow entity and added workflow to the diagram.

### CODE REVIEW

**Review by daniilsavchuk — APPROVED** [review]
Looks that a lot of code was changed. But mostly all constructions have done better then were before. 
Thank you! Great job!

**Comment by sidoruka** [comment]
@voidest , could you please rebase this PR onto #30 ?
Also it would be nice to add some words on this feature to the Demo app doc: [ demo-app-edit-visual.md ](https://github.com/epam/pipeline-builder/blob/dev/docs/general/demo-app-edit-visual.md) . Could you add this too to this PR?

**Comment by voidest** [comment]
@sidoruka, done. I've also added methods to enable/disable ports on a whole diagram.

**Comment by daniilsavchuk** [comment]
@voidest @sidoruka Is the last comment means that we have to add the methods corresponding GUI buttons on demo stend?

**Comment by sidoruka** [comment]
@voidest , thanks a lot. 
@daniilsavchuk , sure. I'll merge this PR and after that could you please add appropriate button to the upper-left toolbar of the demo-app. I.e. by default all links shall be hidden, toggling "Show workflow-level links" button shall visual all links and vice versa.

**Comment by daniilsavchuk** [comment]
@sidoruka Yes of course! I will inform you as soon I'll be able to do that

**Pull request merged**
