### PR TITLE
Feature/graph layout

### PR DESCRIPTION
**Pull request by voidest**
## General idea

This pull request provides an opportunity to layout compound graphs via jointjs. At the moment the layouting is limited - links to nodes that have embeds were prohibited. Such behavour blocks our features like group steps with their own inputs (e.g. scatter, conditional calls) mentioned in #9. Provided changes allow us to layout diverse compound graphs. 

## Changes

Refactored Visual Step, Group and Link to fit the Backbone model. This refactoring enabled the usage of standard clone methods and allowed the creation of temporary graph that has modified links. When that temporary graph is arranged, the layout is applied to the elements of the current graph.

**NOTE** - please let me know before PR will be merged. I have to select suitable package.json version for npm registry.

### CODE REVIEW

**Review by daniilsavchuk — APPROVED** [review]
Looks very good!

Thank you so much for your "deep derived" effort

**Review by paulsmirnov — APPROVED** [review]
Nice trick.

**Comment by sidoruka** [comment]
@voidest , could you please provide a full test sample for this fix? i.e. link to a full WDL script and expected results of it's usage.

**Comment by voidest** [comment]
@sidoruka, this pr does not actually fix any visible issue. It just enables the layouting of some specific compound graphs, which we avoided to use earlier due to dagre limitation. In particular, with these changes we can use group calls (e.g. scatter) with their own ports and connect them to child steps (of course, after proper changes are made in the Model and parser).

**Comment by sidoruka** [comment]
@voidest , ok thanks for clarification.

**Pull request merged**
